### ISSUE TITLE
String substitution problem

### ISSUE THREAD

**Issue by diegocr** [meganz/megalogger#3]
Apparently `MegaLogger` doesn't support _string substitutions_ as the former `console` does.

I.e:

``` js
> MegaLogger.getLogger('foo').info('Adding %d tasks', 33)
< 2015-6-15 19:11:8.715 - foo - INFO Adding %d tasks 33

> console.info('Adding %d tasks', 33)
< Adding 33 tasks
```

Initially i thought it might be a problem while applying css styles, but it doesn't seem so:

``` js
> console.log("%cAdding %d tasks", "color: red; font-style: italic", 22);
< Adding 22 tasks
```

**Comment by lpetrov** [comment]
MegaLogger doesn't support string substitutions.
MegaLogger only support the "multiple arguments" trick, which will combine all passed arguments into 1 string and redirect it to the console.*.

I'm wondering, is that a feature which is important/really needed?
What is the differerence of just doing .info('Adding', yourVar, 'tasks'); <- for me, this feels a bit more easy to read/understand and modify/refactor in later stages of development, then the string formatting syntax.

PS: I was thinking about adding support like python's string formatting.... e.g. %(varName)d, but its... too complicated and totally not related to the actual logger code main principle - KISS.

**Comment by diegocr** [comment]
> I'm wondering, is that a feature which is important/really needed?

Well, we can workaround it - as you pointed - of course, however i'll love if `MegaLogger` has the same features than `console` -- specially useful if you're refactoring a lot of code to use `MegaLogger` as i'm doing these days.

Personally i see more readable `"Adding %d tasks"` than `'Adding', yourVar, 'tasks'` (taking into account that might be long strings and the vars potentially overlooked around them)

afaics, this can be solved easily, check this:

![152815175843](https://cloud.githubusercontent.com/assets/734313/8705846/92dfafcc-2b2c-11e5-90a7-555c7fc1f9a0.gif)

We just have to merge `args[2]` into `args[0]`... this will turn the whole line colored, though.

**Comment by lpetrov** [comment]
I like your fix, which does type checking first, but still... this may be a bit tricky code to maintain.
If you had it tested, on both browser + nodejs environment (we use megalogger in tests too), then just tell me and i will merge your request.

**Comment by lpetrov** [comment]
Also, can you write a unit test that covers this new funcs please ? :)

**Comment by diegocr** [comment]
I didn't previously tested it on nodejs, but i did now.

nodejs doesn't support string substitutions so i added support for that, also fixed the unit tests and added new ones for my stuff.

 Check the last four commits on my PR, you'll notice i got rid of the dependencies (these weren't really required and just bloating the lib) Hence, we no longer need to use browserify to build dist files, `lib/megalogger.js` is ready to go as-is :)
